### ISSUE TITLE
Configuration input

### ISSUE THREAD

**Issue by martinnec** [martinnec/kgbrowser#1]
It must be possible to specify a configuration IRI to configure behaviour.

The configuration IRI is specified manually by the user. The configuration IRI can be changed at any time by the user. Only one configuration IRI can be entered. If the configuration IRI is changed by the user, only this configuration is considered. The previous one is forgotten.

**Comment by sstenchlak** [comment]
When the configuration IRI is changed, what should happen with already loaded resources?

Especially talking about expansions, which transitively depends on the view and the configuration IRI. I need to track them somehow because every expansion can be filtered or removed at any time (that is not your requirement, just mine feature). So, when the user opens a node menu (as described in #7) the  “old” expansions should still be listed there.

Is it possible (in the future) that multiple configurations are applied, when they only affects view sets?

**Comment by martinnec** [comment]
Changing congiguration IRI means that everything is forgotten. When the user changes the configuration IRI, the tool shall ask the user to save the current state, see the new issue #11
